import type { Category, MenuItem } from "./types"

export const categories: Category[] = [
  { id: "drinks", name: "المشروبات", nameEn: "Drinks", icon: "coffee" },
  { id: "sandwiches", name: "السندويشات", nameEn: "Sandwiches", icon: "sandwich" },
  { id: "pastries", name: "المعجنات", nameEn: "Pastries", icon: "croissant" },
  { id: "salads", name: "السلطات", nameEn: "Salads", icon: "salad" },
  { id: "desserts", name: "الحلويات", nameEn: "Desserts", icon: "cake" },
]

export const menuItems: MenuItem[] = [
  // Drinks
  {
    id: "d1",
    name: "قهوة عربية",
    nameEn: "Arabic Coffee",
    description: "قهوة عربية تقليدية مع الهيل",
    price: 5,
    categoryId: "drinks",
    available: true,
  },
  {
    id: "d2",
    name: "شاي أحمر",
    nameEn: "Black Tea",
    description: "شاي أسود مع النعناع",
    price: 3,
    categoryId: "drinks",
    available: true,
  },
  {
    id: "d3",
    name: "كابتشينو",
    nameEn: "Cappuccino",
    description: "إسبريسو مع حليب مخفوق",
    price: 8,
    categoryId: "drinks",
    available: true,
  },
  {
    id: "d4",
    name: "عصير برتقال طازج",
    nameEn: "Fresh Orange Juice",
    description: "عصير برتقال طبيعي 100%",
    price: 10,
    categoryId: "drinks",
    available: true,
  },
  {
    id: "d5",
    name: "ماء معدني",
    nameEn: "Mineral Water",
    description: "مياه معدنية طبيعية",
    price: 2,
    categoryId: "drinks",
    available: true,
  },
  
  // Sandwiches
  {
    id: "s1",
    name: "سندويش دجاج مشوي",
    nameEn: "Grilled Chicken Sandwich",
    description: "دجاج مشوي مع الخضار والصوص",
    price: 18,
    categoryId: "sandwiches",
    available: true,
  },
  {
    id: "s2",
    name: "سندويش تونة",
    nameEn: "Tuna Sandwich",
    description: "تونة طازجة مع الخضار",
    price: 15,
    categoryId: "sandwiches",
    available: true,
  },
  {
    id: "s3",
    name: "سندويش فلافل",
    nameEn: "Falafel Sandwich",
    description: "فلافل مقرمش مع الطحينة",
    price: 12,
    categoryId: "sandwiches",
    available: true,
  },
  {
    id: "s4",
    name: "سندويش جبن حلوم",
    nameEn: "Halloumi Sandwich",
    description: "جبن حلوم مشوي مع الخضار",
    price: 16,
    categoryId: "sandwiches",
    available: false,
  },
  
  // Pastries
  {
    id: "p1",
    name: "كرواسون زبدة",
    nameEn: "Butter Croissant",
    description: "كرواسون فرنسي طازج",
    price: 8,
    categoryId: "pastries",
    available: true,
  },
  {
    id: "p2",
    name: "فطيرة جبن",
    nameEn: "Cheese Pie",
    description: "فطيرة محشوة بالجبن",
    price: 10,
    categoryId: "pastries",
    available: true,
  },
  {
    id: "p3",
    name: "سمبوسة لحم",
    nameEn: "Meat Samosa",
    description: "سمبوسة محشوة باللحم المفروم",
    price: 6,
    categoryId: "pastries",
    available: true,
  },
  
  // Salads
  {
    id: "sa1",
    name: "سلطة سيزر",
    nameEn: "Caesar Salad",
    description: "خس روماني مع صوص سيزر والخبز المحمص",
    price: 20,
    categoryId: "salads",
    available: true,
  },
  {
    id: "sa2",
    name: "سلطة يونانية",
    nameEn: "Greek Salad",
    description: "خضار طازجة مع جبن فيتا",
    price: 18,
    categoryId: "salads",
    available: true,
  },
  {
    id: "sa3",
    name: "تبولة",
    nameEn: "Tabbouleh",
    description: "بقدونس طازج مع البرغل والطماطم",
    price: 12,
    categoryId: "salads",
    available: true,
  },
  
  // Desserts
  {
    id: "de1",
    name: "كنافة",
    nameEn: "Kunafa",
    description: "كنافة نابلسية بالجبن",
    price: 15,
    categoryId: "desserts",
    available: true,
  },
  {
    id: "de2",
    name: "بسبوسة",
    nameEn: "Basbousa",
    description: "بسبوسة بالقطر والمكسرات",
    price: 10,
    categoryId: "desserts",
    available: true,
  },
  {
    id: "de3",
    name: "تشيز كيك",
    nameEn: "Cheesecake",
    description: "تشيز كيك كلاسيكي",
    price: 18,
    categoryId: "desserts",
    available: true,
  },
]
